# Generated by Django 5.2.1 on 2025-07-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='new',
            table='news',
        ),
    ]
