# Generated by Django 5.2.1 on 2025-07-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_new_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='new',
            table=None,
        ),
    ]
