# Generated by Django 5.2.1 on 2025-08-17 10:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_information',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
