# Generated by Django 5.2.2 on 2025-08-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivered_address',
            new_name='adress1',
        ),
        migrations.AlterField(
            model_name='order',
            name='phon_num',
            field=models.CharField(unique=True, verbose_name='Номер телефона'),
        ),
    ]
