# Generated by Django 5.2.1 on 2025-08-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_delivered_address_order_adress1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='adress1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='postal_code',
        ),
    ]
